// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/activities": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "取得所有配對活動的列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理員"
                ],
                "summary": "取得配對活動列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.Activity"
                            }
                        }
                    },
                    "500": {
                        "description": "無法取得活動列表",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "建立新的配對活動",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理員"
                ],
                "summary": "建立新的配對活動",
                "parameters": [
                    {
                        "description": "配對活動資訊",
                        "name": "activity",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Activity"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main.Activity"
                        }
                    },
                    "400": {
                        "description": "無效的請求資料",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "無法建立活動",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/activities/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "更新指定ID的配對活動",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理員"
                ],
                "summary": "更新配對活動",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "活動ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "配對活動資訊",
                        "name": "activity",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Activity"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Activity"
                        }
                    },
                    "400": {
                        "description": "無效的請求資料",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "無法更新活動",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "刪除指定ID的配對活動",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理員"
                ],
                "summary": "刪除配對活動",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "活動ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "活動已刪除",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "無效的活動 ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "無法刪除活動",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/locations": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "取得所有地點的列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理員"
                ],
                "summary": "取得地點列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.Location"
                            }
                        }
                    },
                    "500": {
                        "description": "無法取得地點列表",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "建立新的地點",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理員"
                ],
                "summary": "建立新的地點",
                "parameters": [
                    {
                        "description": "地點資訊",
                        "name": "location",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Location"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main.Location"
                        }
                    },
                    "400": {
                        "description": "無效的請求資料",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "無法建立地點",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/locations/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "更新指定ID的地點",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理員"
                ],
                "summary": "更新地點",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "地點ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "地點資訊",
                        "name": "location",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Location"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Location"
                        }
                    },
                    "400": {
                        "description": "無效的請求資料",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "無法更新地點",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "刪除指定ID的地點",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理員"
                ],
                "summary": "刪除地點",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "地點ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "地點已刪除",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "無效的地點 ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "無法刪除地點",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/{provider}": {
            "get": {
                "description": "開始 Facebook 或 Instagram OAuth 流程",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "認證"
                ],
                "summary": "開始 OAuth 流程",
                "parameters": [
                    {
                        "type": "string",
                        "description": "OAuth 提供者 (facebook 或 instagram)",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "重定向到 OAuth 提供者",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/{provider}/callback": {
            "get": {
                "description": "處理 OAuth 提供者的回調",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "認證"
                ],
                "summary": "OAuth 回調處理",
                "parameters": [
                    {
                        "type": "string",
                        "description": "OAuth 提供者 (facebook 或 instagram)",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "重定向到首頁",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "OAuth 回調錯誤",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/logout": {
            "get": {
                "description": "登出使用者並清除 session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "認證"
                ],
                "summary": "處理登出",
                "responses": {
                    "302": {
                        "description": "重定向到首頁",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/organizer/matches/{id}/participants/{participant_id}/approve": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "開局者審核通過指定配對局的參與者",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "開局者"
                ],
                "summary": "審核通過參與者",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "配對局ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "參與者ID",
                        "name": "participant_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.MatchParticipant"
                        }
                    },
                    "400": {
                        "description": "無效的配對局 ID 或參與者 ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "無法審核通過參與者",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/organizer/matches/{id}/participants/{participant_id}/reject": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "開局者審核拒絕指定配對局的參與者",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "開局者"
                ],
                "summary": "審核拒絕參與者",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "配對局ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "參與者ID",
                        "name": "participant_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.MatchParticipant"
                        }
                    },
                    "400": {
                        "description": "無效的配對局 ID 或參與者 ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "無法審核拒絕參與者",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/profile": {
            "get": {
                "description": "取得使用者資訊",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "使用者"
                ],
                "summary": "取得使用者資訊",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.User"
                        }
                    },
                    "401": {
                        "description": "未登入",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "無法取得使用者資訊",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/review-like/reviews/{id}/dislike": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "對指定ID的評論進行倒讚",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "評論"
                ],
                "summary": "倒讚評論",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "評論ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main.ReviewLike"
                        }
                    },
                    "400": {
                        "description": "無效的評論 ID 或已倒讚",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "無法倒讚評論",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/review-like/reviews/{id}/like": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "對指定ID的評論進行點讚",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "評論"
                ],
                "summary": "點讚評論",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "評論ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main.ReviewLike"
                        }
                    },
                    "400": {
                        "description": "無效的評論 ID 或已點讚",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "無法點讚評論",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/review/matches/{id}": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "建立對指定配對局中其他參與者的評分與留言",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "評分"
                ],
                "summary": "建立評分與留言",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "配對局ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "評分與留言資訊",
                        "name": "review",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Review"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main.Review"
                        }
                    },
                    "400": {
                        "description": "無效的請求資料或已評分過",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "無法建立評分記錄",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/user/matches": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "取得所有時間未到且狀態為open的配對列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "使用者"
                ],
                "summary": "取得時間未到的配對列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.Match"
                            }
                        }
                    },
                    "500": {
                        "description": "無法取得配對列表",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "建立新的配對局 (開局)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "使用者"
                ],
                "summary": "建立新的配對局",
                "parameters": [
                    {
                        "description": "配對局資訊",
                        "name": "match",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Match"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main.Match"
                        }
                    },
                    "400": {
                        "description": "無效的請求資料",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "無法建立配對局",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/user/matches/{id}/join": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "參與指定ID的配對局",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "使用者"
                ],
                "summary": "參與配對",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "配對局ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main.MatchParticipant"
                        }
                    },
                    "400": {
                        "description": "無效的配對局 ID 或已參與",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "無法參與配對局",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/user/past-matches": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "取得該使用者參與過的已完成的配對局列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "使用者"
                ],
                "summary": "取得過去參與的配對列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.Match"
                            }
                        }
                    },
                    "500": {
                        "description": "無法取得過去參與的配對列表",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.Activity": {
            "description": "配對活動資訊",
            "type": "object",
            "properties": {
                "created_by": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "location": {
                    "$ref": "#/definitions/main.Location"
                },
                "location_id": {
                    "type": "integer"
                },
                "target_count": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "main.Location": {
            "description": "地點資訊",
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "main.Match": {
            "description": "配對局資訊",
            "type": "object",
            "properties": {
                "activity": {
                    "$ref": "#/definitions/main.Activity"
                },
                "activity_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "match_time": {
                    "type": "string"
                },
                "organizer": {
                    "$ref": "#/definitions/main.User"
                },
                "organizer_id": {
                    "type": "integer"
                },
                "status": {
                    "description": "open, closed, completed",
                    "type": "string"
                }
            }
        },
        "main.MatchParticipant": {
            "description": "配對參與者資訊",
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "joined_at": {
                    "type": "string"
                },
                "match": {
                    "$ref": "#/definitions/main.Match"
                },
                "match_id": {
                    "type": "integer"
                },
                "status": {
                    "description": "pending, approved, rejected",
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/main.User"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "main.Review": {
            "description": "評分與留言資訊",
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "match": {
                    "$ref": "#/definitions/main.Match"
                },
                "match_id": {
                    "type": "integer"
                },
                "reviewee": {
                    "$ref": "#/definitions/main.User"
                },
                "reviewee_id": {
                    "type": "integer"
                },
                "reviewer": {
                    "$ref": "#/definitions/main.User"
                },
                "reviewer_id": {
                    "type": "integer"
                },
                "score": {
                    "description": "3-5分",
                    "type": "integer"
                }
            }
        },
        "main.ReviewLike": {
            "description": "評論點讚/倒讚資訊",
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "is_like": {
                    "description": "true: 點讚, false: 倒讚",
                    "type": "boolean"
                },
                "review": {
                    "$ref": "#/definitions/main.Review"
                },
                "review_id": {
                    "type": "integer"
                },
                "user": {
                    "$ref": "#/definitions/main.User"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "main.User": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "created_at": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "social_id": {
                    "type": "string"
                },
                "social_provider": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "買一送一配對網站 API",
	Description:      "這是一個買一送一配對網站的API文檔",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
